### ISSUE TITLE
Heartbeat

### ISSUE THREAD

**Issue by smokinguns** [mfeckie/phoenix_wings#10]
Thanks for putting this package together.  I'm currently getting an error not being able to match the heartbeat message. Should the heartbeat be optional? It looks the heartbeat option was removed from the phoenix server https://github.com/phoenixframework/phoenix/commit/7b252f42cc8552496a5ebd392f59a008ef6c98a9.  Looking in phoenix.js it looks like there is a skipHeartbeat. I'm wondering if it exists for backwards compatibility. I haven't looked much deeper and I could be reading it wrong.

**Comment by mfeckie** [comment]
It's possible that the API has changed since I wrote this library.

I'd be happy to accept a PR which allows for skipping.

Currently I don't have a great deal of time to look into doing so myself.

**Comment by smokinguns** [comment]
@mfeckie For sure. This gives me some motivation to pull it down and experiment. Your efforts have saved me a huge amount of time, as I had sat down to write this exact library.

**Comment by mfeckie** [comment]
Is this still an issue?
