### ISSUE TITLE
why endpoint from WS://****** to http://******

### ISSUE THREAD

**Issue by tmacLiu001** [mfeckie/phoenix_wings#15]
WebSocket connection to ws://192.168.187.25:4001/socket?id=1234&vsn=2.0.0 failed!: WebSocketException: Connection to 'http://192.168.187.25:4001/socket?id=1234&vsn=2.0.0#' was not upgraded to websocket

**Comment by mfeckie** [comment]
There's not enough information to figure out what the problem is here.

Please can you share what version of Phoenix you're trying to connect to?  Also, does this only happen when connecting via Dart / Flutter, or does it affect you if you use the Phoenix.js client in a browser?

**Comment by tmacLiu001** [comment]
thank, you! I already fixed it . it just because  of `...was not upgraded to websocket`.  phoenix version: "~> 1.4.3"

**Comment by tblakey89** [comment]
@fightingLT How did you fix it?

**Comment by albydarned** [comment]
I'm also wondering how this was fixed @fightingLT

**Comment by alexfilatov** [comment]
@tmacLiu001 care to share how exactly you fixed that? thanks

**Comment by redDwarf03** [comment]
any update or info ?

**Comment by albydarned** [comment]
I remember going through this and fixing it as well but can't quite remember... Heres my working code...

```
Map<String, String> params = {
  "token": token
};
PhoenixSocketOptions socketOptions = PhoenixSocketOptions(params: params);

_connectSocket("wss://app.url.com:443/socket/websocket", socketOptions)
  .then((PhoenixSocket socket) {
    _socket = socket;
    _channel = _socket.channel("my:channel");

    _channel.on("event", _function);

    _channel.join();
  });
});
```

**Comment by redDwarf03** [comment]
> I remember going through this and fixing it as well but can't quite remember... Heres my working code...
> 
> ```
> Map<String, String> params = {
>   "token": token
> };
> PhoenixSocketOptions socketOptions = PhoenixSocketOptions(params: params);
> 
> _connectSocket("wss://app.url.com:443/socket/websocket", socketOptions)
>   .then((PhoenixSocket socket) {
>     _socket = socket;
>     _channel = _socket.channel("my:channel");
> 
>     _channel.on("event", _function);
> 
>     _channel.join();
>   });
> });
> ```

Thank you but I use Absinthe on top of Phoenix so I'm not linking your example to mine. I hope it will help other developers though :)

**Comment by redDwarf03** [comment]
I think I find
it doesn't work when I coded ``` AbsintheSocket _socket = AbsintheSocket('ws://' + host + '/socket');```
But then I added web socket, it worked better: ``` AbsintheSocket _socket = AbsintheSocket('ws://' + host + '/socket/websocket');```
