### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by allenwyma** [mfeckie/phoenix_wings#27]
Is it possible to update with null-safety? This is one of the packages stopping us from going to null safety.

**Comment by mfeckie** [comment]
@HangingClowns I'm not doing any active flutter work at the moment so don't have bandwidth to work on this request.

I'd be happy to accept a PR, but I'm not able to commit to doing the work myself

**Comment by allenwyma** [comment]
Okay, I may attempt to do this. I haven't tried it before. :)

**Comment by MapperMalte** [comment]
> Okay, I may attempt to do this. I haven't tried it before. :)

I am interested in this as well. Are you already done? Would you mind merging it here?

**Comment by allenwyma** [comment]
I haven’t had a moment. If you wanted to kick it off you can leave a link here and I may join in.

**Comment by macoshita** [comment]
I'm sorry, I didn't see this.
I made a PR to fix this.

https://github.com/mfeckie/phoenix_wings/pull/28

**Comment by mfeckie** [comment]
Fixed by https://github.com/mfeckie/phoenix_wings/pull/28
