### ISSUE TITLE
Possible incompatibility with phoenix.js

### ISSUE THREAD

**Issue by gmlewis** [mfeckie/phoenix_wings#6]
First off, thank you for this great package... I'm learning a lot from it!
Secondly, I'm a complete newbie to Flutter, Elixir, Phoenix, Dart, and websockets, so take all of this with a grain of salt.

While trying to put together a simple Flutter chat app talking to this simple Phoenix chat server:
https://github.com/stevegrossi/phoenix_chat

I ran into what appears to be an incompatibility with the phoenix.js version for the `"phx_join"` message.

Specifically, my Flutter app was sending this:
```
payload: "[\"2\",\"2\",\"room:lobby\",\"phx_join\",{}]",
(phoenix) lib/phoenix/socket/message.ex:21: Phoenix.Socket.Message.from_map!(["2", "2", "room:lobby", "phx_join", %{}])
```

but the phoenix.js version was sending this:
```
payload: "{\"topic\":\"room:lobby\",\"event\":\"phx_join\",\"payload\":{},\"ref\":\"73\"}",
```

When I changed `phoenix_message.dart` from this:

```dart
  String toJSON() {
    return json.encode([joinRef, ref, topic, event, payload]);
  }
```

to this:

```dart
  String toJSON() {
    //GML return json.encode([joinRef, ref, topic, event, payload]);
    var msg = {
      'joinRef': joinRef,
      'ref': ref,
      'topic': topic,
      'event': event,
      'payload': payload,
    };
    return JSON.encode(msg);
  }
```

the `phx_join` started working. Any ideas why this might be the case?

**Comment by mfeckie** [comment]
Thanks for the feedback.  I'll take a look.

**Comment by mfeckie** [comment]
Hey @gmlewis Could you share the flutter code you were using to try and connect?

As far as I can tell the payload is correct.

I used this https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/socket/serializers/v2_json_serializer.ex#L12-L39 as the reference for structuring the payload.

**Comment by gmlewis** [comment]
Thanks, @mfeckie. I'm requesting permission to share my example. I'll report when I hear back.

**Comment by philipgiuliani** [comment]
It seems that your project is using the v1 serializer instead of the v2.
See: https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/socket/serializers/v1_json_serializer.ex#L13

I'm not sure in which Phoenix version they updated to the v2 json serializer. I think it is configurable somewhere. What Phoenix version are you using? Any chance to upgrade?

**Comment by gmlewis** [comment]
Oh!  I see what you are saying. I used this chat application:
https://github.com/stevegrossi/phoenix_chat/blob/master/mix.exs#L33
and that looks like Phoenix 1.2.
I'll see if I can upgrade.  Thanks, @philipgiuliani!

**Comment by gmlewis** [comment]
Starting with the `mix.exs` file from the last comment, I updated the `deps` to this:

```elixir
  defp deps do
    [{:phoenix, "~> 1.3.2"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.2"},
     {:plug, "~>1.5.1"}, # GML
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.10"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.11"},
     {:cowboy, "~> 1.0"}]
  end
```

Does this look correct?

If it does, then I'm surprised that my (modified) `phoenix_wings` still works!
I also added Phoenix Presence support and it seems to work.
I need to do a code review at work and hopefully soon I can share my changes.

**Comment by mfeckie** [comment]
Without seeing more of the application you're building it's not possible to know what serializer is being used.

**Comment by gmlewis** [comment]
I believe I have finally figured out what is going on.

The [phoenix_chat](https://github.com/gmlewis/phoenix_chat) server sends payload messages that are simple strings and not maps.

When I make [these changes](https://github.com/gmlewis/phoenix_wings/commit/0522ebbdbd8f30240de6a10a485f179c1ea808b8) to phoenix_wings, I'm able to use it with the `phoenix_chat` server.

As an aside, I went ahead and implemented [`PhoenixPresence`](https://github.com/gmlewis/flutter_chat/blob/master/lib/phoenix_presence.dart) by translating the JavaScript `phoenix.js` to Dart. 

Let me know if you would like a PR for the `Map` -> `dynamic` changes.

**Comment by mfeckie** [comment]
I'm gonna close this as stale now, but PR for Map -> dynamic still welcome
