### ISSUE TITLE
socket.disconnect does not stop the connect loop

### ISSUE THREAD

**Issue by philipgiuliani** [mfeckie/phoenix_wings#7]
If the server is not available, there is no way to stop the `.connect()` retries.
I expect that if I call `socket.disconnect` the `connect` method will stop retrying.

You can reproduce this by using an invalid socket url.

**Comment by mfeckie** [comment]
Is this still an issue?

**Comment by philipgiuliani** [comment]
Hi, i will update the library in my project soon, and try to reproduce the issue.

**Comment by Iccr** [comment]
this is still an issue. socket.disconnect does not stop the loop. is there any update in this?

**Comment by mfeckie** [comment]
I hope this is fixed in the latest release. Please try 0.2.2

I'm not actively doing dart/flutter work at the moment, so I'm not able to devote a lot of time to this project
